[package]
name = "glass-pipeline"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
glass-engine = { path = "../engine" }
log = { version = "0.4", default-features = false }
tokio = { version = "1.1", features = ["full"] }
